# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdc877a16eea300705674db586b07879ae99607a706ad22351f57869ef15e64d5321de075ecfa687dab565686223b0419bd688216d2043f492561a4101b3d437

test:
  secret_key_base: 20b7e0137087096e256bdfe5bf0c9888abb8f5e079702b058865f82f55c9b4178d55eadc7af05abd16e4e16049f1ad4084f9a89532996ee47192abde124d1d70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
